apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-memorystore-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Google Cloud Memorystore Terraform Module
    source:
      repo: https://github.com/yogitaupadhyay/terraform-google-memorystore.git
      sourceType: git
  ui:
    input:
      variables:
        alternative_location_id:
          name: alternative_location_id
          title: Alternative Location Id
        auth_enabled:
          name: auth_enabled
          title: Auth Enabled
        authorized_network:
          name: authorized_network
          title: Authorized Network
        connect_mode:
          name: connect_mode
          title: Connect Mode
        customer_managed_key:
          name: customer_managed_key
          title: Customer Managed Key
        display_name:
          name: display_name
          title: Display Name
        enable_apis:
          name: enable_apis
          title: Enable Apis
        labels:
          name: labels
          title: Labels
        location_id:
          name: location_id
          title: Location Id
        maintenance_policy:
          name: maintenance_policy
          title: Maintenance Policy
        memory_size_gb:
          name: memory_size_gb
          title: Memory Size Gb
        name:
          name: name
          title: Name
        persistence_config:
          name: persistence_config
          title: Persistence Config
        project_id:
          name: project_id
          title: Project Id
        read_replicas_mode:
          name: read_replicas_mode
          title: Read Replicas Mode
        redis_configs:
          name: redis_configs
          title: Redis Configs
        redis_version:
          name: redis_version
          title: Redis Version
        region:
          name: region
          title: Region
        replica_count:
          name: replica_count
          title: Replica Count
        reserved_ip_range:
          name: reserved_ip_range
          title: Reserved Ip Range
        secondary_ip_range:
          name: secondary_ip_range
          title: Secondary Ip Range
        tier:
          name: tier
          title: Tier
        transit_encryption_mode:
          name: transit_encryption_mode
          title: Transit Encryption Mode
